# Домашнее задание 

   ●   Создайте случайную матрицу А1 размерностью 5 на 5 

   ●   Транспонируйте матрицу A1 

   ●   Найдите обратную матрицу для А1 

   ●   Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

   ●   Создайте нулевую матрицу размерности 3 на 3 

   ●   Для всех полученных матриц найдите: определитель, ранг и собственные значения 

In [3]:
# Необходимая библиотека...
import numpy as np

In [6]:
# Создаю случайную матрицу А1 размерностью 5 на 5
A1=np.random.random((5,5))
A1

array([[0.00853445, 0.06723131, 0.81600904, 0.84717823, 0.23670117],
       [0.7389008 , 0.44505614, 0.17245404, 0.41522343, 0.21526545],
       [0.73321421, 0.01214914, 0.07701478, 0.13220315, 0.94759658],
       [0.75408225, 0.5431664 , 0.36026917, 0.76939263, 0.44537235],
       [0.35245107, 0.62088109, 0.87705033, 0.01485381, 0.57057337]])

In [8]:
# Транспонирую матрицу A1
# замена строк и столбцов местами
A1tr=np.transpose(A1)
A1tr

array([[0.00853445, 0.7389008 , 0.73321421, 0.75408225, 0.35245107],
       [0.06723131, 0.44505614, 0.01214914, 0.5431664 , 0.62088109],
       [0.81600904, 0.17245404, 0.07701478, 0.36026917, 0.87705033],
       [0.84717823, 0.41522343, 0.13220315, 0.76939263, 0.01485381],
       [0.23670117, 0.21526545, 0.94759658, 0.44537235, 0.57057337]])

In [10]:
# Нахожу обратную матрицу для А1
A1obr=np.linalg.inv(A1)
A1obr

array([[ 0.81674683,  4.32959534,  0.5521722 , -3.32510814, -0.29384911],
       [-1.71058416, -3.05014747, -1.08031721,  3.70045696,  0.7660931 ],
       [ 1.36668999,  2.6091075 ,  0.11543095, -2.94347786,  0.55455418],
       [ 0.20081075, -1.38430267, -0.21616576,  1.87569379, -0.66614363],
       [-0.74912828, -3.3298926 ,  0.66267897,  2.5029405 ,  0.26541293]])

In [12]:
# Создаю диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4
# единичная матрица:
AI=np.eye(4)
AI

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# случайная матрица A2 размерности 4 на 4
A2=np.random.random((4,4))
A2

array([[0.03200823, 0.59230656, 0.39119745, 0.1830052 ],
       [0.07229437, 0.82284605, 0.98648022, 0.63692841],
       [0.58839532, 0.17903347, 0.0833731 , 0.41571423],
       [0.28298142, 0.51970777, 0.04998025, 0.42336111]])

In [16]:
# перемножаю две предыдущих матрицы
A3=AI@A2
A3
# То есть при умножении единичной матрицы на матрицу получается та же самая матрица:

array([[0.03200823, 0.59230656, 0.39119745, 0.1830052 ],
       [0.07229437, 0.82284605, 0.98648022, 0.63692841],
       [0.58839532, 0.17903347, 0.0833731 , 0.41571423],
       [0.28298142, 0.51970777, 0.04998025, 0.42336111]])

In [17]:
# поменял при умножении матрицы местами
# получается: при умножении матрицы на единичную матрицу получается та же самая матрица:
A4=A2@AI
A4

array([[0.03200823, 0.59230656, 0.39119745, 0.1830052 ],
       [0.07229437, 0.82284605, 0.98648022, 0.63692841],
       [0.58839532, 0.17903347, 0.0833731 , 0.41571423],
       [0.28298142, 0.51970777, 0.04998025, 0.42336111]])

In [19]:
# Создаю нулевую матрицу размерности 3 на 3
А0=np.zeros([4,4])
А0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Для всех полученных матриц найдите: определитель, ранг и собственные значения

In [20]:
# Матрица A1
# определитель:
np.linalg.det(A1)

-0.11731563230940437

In [21]:
# ранг
np.linalg.matrix_rank(A1)

5

In [22]:
# собственные значения и вектора собственных значений:
np.linalg.eig(A1)

(array([ 2.23572802+0.j        , -1.00414631+0.j        ,
        -0.03169438+0.27091466j, -0.03169438-0.27091466j,
         0.70237841+0.j        ]),
 array([[-0.41663983+0.j        , -0.59064713+0.j        ,
          0.55604261+0.j        ,  0.55604261-0.j        ,
         -0.07709254+0.j        ],
        [-0.3956692 +0.j        ,  0.23446114+0.j        ,
         -0.38803093-0.38316128j, -0.38803093+0.38316128j,
         -0.48999534+0.j        ],
        [-0.3711004 +0.j        ,  0.68116905+0.j        ,
          0.34474719+0.07360756j,  0.34474719-0.07360756j,
          0.45519798+0.j        ],
        [-0.58455196+0.j        ,  0.12654536+0.j        ,
         -0.19970823+0.11526345j, -0.19970823-0.11526345j,
         -0.58797885+0.j        ],
        [-0.43639504+0.j        , -0.34082098+0.j        ,
         -0.45800143+0.07894936j, -0.45800143-0.07894936j,
          0.44837148+0.j        ]]))

In [23]:
# только собственные значения:
np.linalg.eigvals(A1)

array([ 2.23572802+0.j        , -1.00414631+0.j        ,
       -0.03169438+0.27091466j, -0.03169438-0.27091466j,
        0.70237841+0.j        ])

In [27]:
# Матрица A1tr
# определитель:
A1tr_opred=np.linalg.det(A1tr)
print(f'Определитель матрицы = {A1tr_opred}')

# ранг
A1tr_rang=np.linalg.matrix_rank(A1tr)
print(f'Ранг матрицы = {A1tr_rang}')

# собственные значения:
A1tr_sz=np.linalg.eigvals(A1tr)
print(f'Собственные значения матрицы = {A1tr_sz}')

Определитель матрицы = -0.11731563230940437
Ранг матрицы = 5
Собственные значения матрицы = [ 2.23572802+0.j         -1.00414631+0.j         -0.03169438+0.27091466j
 -0.03169438-0.27091466j  0.70237841+0.j        ]


In [28]:
# Матрица A1obr
# определитель:
A1obr_opred=np.linalg.det(A1obr)
print(f'Определитель матрицы = {A1tr_opred}')

# ранг
A1obr_rang=np.linalg.matrix_rank(A1obr)
print(f'Ранг матрицы = {A1obr_rang}')

# собственные значения:
A1obr_sz=np.linalg.eigvals(A1obr)
print(f'Собственные значения матрицы = {A1obr_sz}')

Определитель матрицы = -0.11731563230940437
Ранг матрицы = 5
Собственные значения матрицы = [-0.42600386+3.64136101j -0.42600386-3.64136101j -0.99587081+0.j
  0.4472816 +0.j          1.42373396+0.j        ]


In [29]:
# Матрица AI
# определитель:
AI_opred=np.linalg.det(AI)
print(f'Определитель матрицы = {AI_opred}')

# ранг
AI_rang=np.linalg.matrix_rank(AI)
print(f'Ранг матрицы = {AI_rang}')

# собственные значения:
AI_sz=np.linalg.eigvals(AI)
print(f'Собственные значения матрицы = {AI_sz}')

Определитель матрицы = 1.0
Ранг матрицы = 4
Собственные значения матрицы = [1. 1. 1. 1.]


In [32]:
# Матрица A0
# определитель:
A0_opred=np.linalg.det(А0)
print(f'Определитель матрицы = {A0_opred}')

# ранг
A0_rang=np.linalg.matrix_rank(А0)
print(f'Ранг матрицы = {A0_rang}')

# собственные значения:
A0_sz=np.linalg.eigvals(А0)
print(f'Собственные значения матрицы = {A0_sz}')

Определитель матрицы = 0.0
Ранг матрицы = 0
Собственные значения матрицы = [0. 0. 0. 0.]


In [37]:
# Матрица A2
# определитель:
A2_opred=np.linalg.det(A2)
print(f'Определитель матрицы = {A2_opred}')

# ранг
A2_rang=np.linalg.matrix_rank(A2)
print(f'Ранг матрицы = {A2_rang}')

# собственные значения:
A2_sz=np.linalg.eigvals(A2)
print(f'Собственные значения матрицы = {A2_sz}')

Определитель матрицы = 0.05066576316778358
Ранг матрицы = 4
Собственные значения матрицы = [ 1.6677884 +0.j         -0.22362284+0.40666558j -0.22362284-0.40666558j
  0.14104577+0.j        ]


In [38]:
# Матрица A3
# определитель:
A3_opred=np.linalg.det(A3)
print(f'Определитель матрицы = {A3_opred}')

# ранг
A3_rang=np.linalg.matrix_rank(A3)
print(f'Ранг матрицы = {A3_rang}')

# собственные значения:
A3_sz=np.linalg.eigvals(A3)
print(f'Собственные значения матрицы = {A3_sz}')

Определитель матрицы = 0.05066576316778358
Ранг матрицы = 4
Собственные значения матрицы = [ 1.6677884 +0.j         -0.22362284+0.40666558j -0.22362284-0.40666558j
  0.14104577+0.j        ]
