## Домашнее задание "Библиотека numpy. Вычислительные задачи"

### Задание 1.

Создайте numpy array с элементами от числа N до 0
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np
number_el = int(input('Введите количество элементов массива N (больше 0): '))
numpy_array = np.arange(number_el-1, -1, -1)

numpy_array

Введите количество элементов массива N (больше 0): 15


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [17]:
import numpy as np
number_el = int(input('Введите количество элементов массива N (больше 0): '))
numpy_array2 = np.diag(np.arange(number_el, -1, -1), k = 0)
# в данном случае можно посчитать просто сумму матрицы (все остальные элементы не по диоганали = 0)
sum_ = np.sum(numpy_array2)
print(numpy_array2)
print(f'\nСумма значений = {sum_}')

Введите количество элементов массива N (больше 0): 11
[[11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]

Сумма значений = 66


In [22]:
# В данном случае использую np.trace()

import numpy as np
number_el = int(input('Введите количество элементов массива N (больше 0): '))
numpy_array2a = np.diag(np.arange(number_el, -1, -1), k = 0)
sum_2a = np.trace(numpy_array2)

print(numpy_array2a)
print(f'\nСумма значений = {sum_2a}')

Введите количество элементов массива N (больше 0): 11
[[11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]

Сумма значений = 66


### Задание 3

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3


In [24]:
import numpy as np
from numpy import linalg as LA

a3 = [[4, 2, 1],
     [1, 3, 0],
     [0, 5, 4]]

b3 = [4, 12, -3]
 
x3 = LA.solve(a, b)
x3


array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

Из материалов занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [2]:
import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

# next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [3]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)

    return np.dot(a, b) / (aLength * bLength)

In [64]:
dict_users = {}

for i in range(0, len(users_stats)):
    dict_users[i] = cosine(users_stats[i], np.array([0, 1, 2, 0, 0, 0]))

ind_users = list(dict_users.values()).index(max(dict_users.values()))

print(f'Косинусы углов между векторами статистики и следующего покупателя = {list(dict_users.values())}\n')

print(f'Самый похожий пользователь № {ind_users}\n\
С максимальным косинусом угла между векторами = {max(dict_users.values())}\n\
И значением статистики = {users_stats[ind_users]}')

Косинусы углов между векторами статистики и следующего покупателя = [0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]

Самый похожий пользователь № 7
С максимальным косинусом угла между векторами = 0.9486832980505138
И значением статистики = [0 1 1 0 0 0]
